### ISSUE TITLE
Error running installer (Windows)

### ISSUE THREAD

**Issue by nvzoll** [antonreshetov/massCode#13]
Release executable `massCode.Setup.0.5.0.exe` fails with the following popup:
```
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: Config schema violation: `bounds` should be object; `sidebarWidth` should be number; `snippetListWidth` should be number; `selectedFolderId` should be string; `selectedFolderIds` should be string; `selectedSnippetId` should be string; `install` should be string
    at ElectronStore._validate (C:\Users\nvz01\AppData\Local\Programs\masscode\resources\app.asar\node_modules\conf\index.js:154:10)
    at new Conf (C:\Users\nvz01\AppData\Local\Programs\masscode\resources\app.asar\node_modules\conf\index.js:121:8)
    at new ElectronStore (C:\Users\nvz01\AppData\Local\Programs\masscode\resources\app.asar\node_modules\electron-store\index.js:23:3)
    at Module.<anonymous> (C:\Users\nvz01\AppData\Local\Programs\masscode\resources\app.asar\dist\electron\main.js:1:4825)
    at n (C:\Users\nvz01\AppData\Local\Programs\masscode\resources\app.asar\dist\electron\main.js:1:124)
    at C:\Users\nvz01\AppData\Local\Programs\masscode\resources\app.asar\dist\electron\main.js:1:928
    at Object.<anonymous> (C:\Users\nvz01\AppData\Local\Programs\masscode\resources\app.asar\dist\electron\main.js:1:937)
    at Module._compile (internal/modules/cjs/loader.js:880:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
    at Module.load (internal/modules/cjs/loader.js:735:32)

[OK]
```

Environment: Windows 10 1903

**Comment by antonreshetov** [comment]
@nvzoll in version 0.5.1 should work, please check. https://github.com/antonreshetov/massCode/releases/tag/v0.5.1

**Comment by nvzoll** [comment]
v0.5.1 installs just fine 👍
